//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HohoTraveltestlagi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdmID { get; set; }
        public string AdmName { get; set; }
        public string AdmEmail { get; set; }
        public string AdmPhNo { get; set; }
        public string Password { get; set; }
    }
}
