//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HohoTraveltestlagi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        public int BookID { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<int> PackID { get; set; }
        public string CustName { get; set; }
        public string CustEmail { get; set; }
        public string CustPhNum { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        //[DataType(DataType.Date)]
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string BookMessage { get; set; }
        public string RekNo { get; set; }
        public string RekName { get; set; }
        public string BookStatus { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<int> BookPrice { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
